name: CivCraft
main: com.avrgaming.civcraft.main.CivCraft
softdepends: [TitleAPI, HolographicDisplays]
version: 1.8.0-Beta7
depend: 

commands:
    town:
        aliases: [t,е, ещцт]
    plot:
        aliases: [p,здще,з]
    resident:
        aliases: [res,куы]
    dbg:
        aliases: []
    accept:
        aliases: [yes,нуы]
    deny:
        aliases: [no,тщ,вутн]
    civ:
        aliases: [сшм]
    tc:
        aliases: [ес]
    cc:
        aliases: [сс]
    ac:
        aliases: [фс]
    gc:
        aliases: [пс]
    ad:
        aliases: [фв]
    build:
        aliases: [b,игшдв,и]
    market:
        aliases: [m]
    select:
        aliases:
    econ:
        aliases: [money,ьщтун,ьщт]
    pay:
        aliases:
    here:
        aliases:
    camp:
        aliases: [сфьз]
    report:
        aliases:
    trade:
        aliases:
    kill:
        aliases:
    team:
        aliases:
    sb:
        aliases:
    wiki:
        aliases:
    map:
        aliases:
    vcc:
        aliases: [campchat]
    donate:
    enderchest:
        aliases: [echest, eechest, eenderchest, endersee, eendersee, ec, eec]
