name: CivCraft
main: com.avrgaming.civcraft.main.CivCraft
softdepends: [HolographicDisplays]
version: 1.8.0-Beta7
depend: 

commands:
    ad:
        aliases: [фв]
    dbg:
        aliases: []
    tc:
        aliases: [ес]
    cc:
        aliases: [сс]
    ac:
        aliases: [фс]
    gc:
        aliases: [пс]
    select:
        aliases:
    pay:
        aliases:
    here:
        aliases:
    report:
        aliases:
    trade:
        aliases:
    kill:
        aliases: [k, л, suicide]
    team:
        aliases:
    sb:
        aliases:
    wiki:
        aliases:
    map:
        aliases:
    vcc:
        aliases: [campchat]
    donate:
    enderchest:
        aliases: [echest, eechest, eenderchest, endersee, eendersee, ec, eec]
